// Ad-hoc driver for the forum verification — not a permanent test.
// Boots the seeded admin + trainer, drives the forum end-to-end:
//   trainer  -> create thread, search, shoutbox, reply, report
//   admin    -> see report, delete reported reply, delete thread
//   anon     -> view both trainers' public profiles
//
// Run with: BASE_URL=http://127.0.0.1:8123 node tests/e2e/forums-verify.mjs

import { chromium } from '@playwright/test';
import fs from 'node:fs/promises';

const BASE = process.env.BASE_URL || 'http://127.0.0.1:8123';
const OUT = '/tmp/forum-verify';
await fs.mkdir(OUT, { recursive: true });

function step(n, msg) { console.log(`\n[${n}] ${msg}`); }
function ok(msg)      { console.log('  ✅ ' + msg); }
function bad(msg)     { console.log('  ❌ ' + msg); process.exitCode = 1; }
function note(msg)    { console.log('  • ' + msg); }

async function login(page, email, pw) {
  await page.goto(BASE + '/login', { waitUntil: 'domcontentloaded' });
  await page.fill('input[name="email"]', email);
  await page.fill('input[name="password"]', pw);
  await Promise.all([
    page.waitForURL(u => !u.toString().includes('/login'), { timeout: 15000, waitUntil: 'domcontentloaded' }),
    page.locator('form[action$="/login"] button[type="submit"]').click(),
  ]);
}

async function main() {
  const browser = await chromium.launch({ channel: 'chrome' });
  const trainerCtx = await browser.newContext();
  const adminCtx   = await browser.newContext();
  const anonCtx    = await browser.newContext();

  const trainer = await trainerCtx.newPage();
  const admin   = await adminCtx.newPage();
  const anon    = await anonCtx.newPage();

  const allErrors = [];
  for (const [name, p] of [['trainer', trainer], ['admin', admin], ['anon', anon]]) {
    p.on('pageerror', e => allErrors.push(`[${name}] JS: ${e.message}`));
    p.on('response', r => {
      try {
        if (new URL(r.url()).host === new URL(BASE).host && r.status() >= 500) {
          allErrors.push(`[${name}] ${r.status()} ${r.url()}`);
        }
      } catch {}
    });
  }

  // ── 1. Trainer logs in & creates a thread ──────────────────────────
  step(1, 'Trainer logs in & creates a thread');
  await login(trainer, 'trainer@poketrade.test', 'password');
  await trainer.goto(BASE + '/forums/new');
  await trainer.screenshot({ path: `${OUT}/01-thread-new.png`, fullPage: true });

  const title = 'VERIFY ' + Date.now();
  const body  = 'Auto-generated by forum verifier. Please ignore.';
  await trainer.selectOption('select[name="forum_category_id"]', { index: 1 });
  await trainer.fill('input[name="title"]', title);
  await trainer.fill('textarea[name="body"]', body);
  await Promise.all([
    trainer.waitForURL(/\/forums\/t\/\d+/, { timeout: 15000, waitUntil: 'domcontentloaded' }),
    trainer.locator('form[action$="/forums"] button[type="submit"]').click(),
  ]);
  const threadUrl = trainer.url();
  if (/\/forums\/t\/\d+/.test(threadUrl)) ok('redirected to thread ' + threadUrl);
  else bad('not redirected to thread, got ' + threadUrl);
  const threadId = threadUrl.match(/\/forums\/t\/(\d+)/)?.[1];
  await trainer.screenshot({ path: `${OUT}/02-thread-created.png`, fullPage: true });

  // ── 2. Search for it on /forums ───────────────────────────────────
  step(2, 'Search /forums?q=… finds the new thread');
  await trainer.goto(BASE + '/forums?q=' + encodeURIComponent(title));
  const matches = await trainer.locator(`a:has-text("${title}")`).count();
  if (matches > 0) ok(`found ${matches} match(es) for "${title}"`);
  else bad('search did not surface the new thread');
  await trainer.screenshot({ path: `${OUT}/03-search.png`, fullPage: true });

  // ── 3. Shoutbox: trainer sends a chat message ─────────────────────
  step(3, 'Shoutbox (live chat) accepts a message');
  await trainer.goto(BASE + '/forums');
  const shoutText = 'verifier shout ' + Date.now();
  await trainer.fill('aside form input[type="text"]', shoutText);
  const shoutResp = trainer.waitForResponse(r => r.url().endsWith('/forums/shoutbox') && r.request().method() === 'POST');
  await trainer.click('aside form button[type="submit"]');
  const sr = await shoutResp;
  if (sr.status() === 201) ok('POST /forums/shoutbox 201');
  else bad('shoutbox POST returned ' + sr.status());
  await trainer.waitForTimeout(200);
  const shoutVisible = await trainer.locator(`aside :text("${shoutText}")`).count();
  if (shoutVisible > 0) ok('message rendered in stream');
  else bad('message not rendered in stream');
  await trainer.screenshot({ path: `${OUT}/04-shoutbox.png`, fullPage: true });

  // ── 4. Trainer leaves a reply on their own thread (admin needs target to delete) ─
  // We need ANOTHER user's reply for the "report" flow (you can't report yourself),
  // so admin will reply, then trainer reports it.
  step(4, 'Admin logs in and replies to the thread');
  await login(admin, 'admin@poketrade.test', 'password');
  await admin.goto(threadUrl);
  const replyText = 'Admin reply ' + Date.now();
  await admin.fill('textarea[name="body"]', replyText);
  await Promise.all([
    admin.waitForLoadState('domcontentloaded'),
    admin.locator('button:has-text("Post reply")').first().click(),
  ]);
  if (await admin.locator(`:text("${replyText}")`).count() > 0) ok('admin reply visible');
  else bad('admin reply not visible');

  // ── 5. Trainer reports the admin's reply ──────────────────────────
  step(5, 'Trainer reports admin reply');
  await trainer.goto(threadUrl);
  // open the report dialog on the reply
  const reportBtn = trainer.locator('article', { hasText: replyText }).getByRole('button', { name: 'Report' });
  await reportBtn.click();
  await trainer.locator('select[name="reason"]:visible').selectOption('spam');
  await trainer.locator('textarea[name="details"]:visible').fill('verifier — spam');
  const reportResp = trainer.waitForResponse(r => r.url().endsWith('/reports') && r.request().method() === 'POST');
  await trainer.locator('button:has-text("Submit report"):visible').click();
  const rr = await reportResp;
  if (rr.status() < 400) ok('report submitted (' + rr.status() + ')');
  else bad('report POST returned ' + rr.status());
  await trainer.screenshot({ path: `${OUT}/05-report-submitted.png`, fullPage: true });

  // ── 6. Admin sees the report in /admin/reports ────────────────────
  step(6, 'Admin sees the report in /admin/reports');
  await admin.goto(BASE + '/admin/reports');
  await admin.screenshot({ path: `${OUT}/06-admin-reports.png`, fullPage: true });
  const seesReport = await admin.locator(':text("verifier — spam")').count();
  if (seesReport > 0) ok('report shows reporter details on admin panel');
  else bad('report not found in admin panel');

  // ── 7. Admin uses "Remove content" to delete the reported reply ──
  step(7, 'Admin clicks Remove content on the open report');
  // intercept the confirm dialog
  admin.once('dialog', d => d.accept());
  const removeForm = admin.locator('form:has(input[value="remove"])').first();
  await removeForm.locator('button:has-text("Remove content")').click();
  await admin.waitForLoadState('domcontentloaded');
  // The reply should be gone from the thread page now.
  await admin.goto(threadUrl);
  const replyGone = await admin.locator(`:text("${replyText}")`).count();
  if (replyGone === 0) ok('reply was deleted by admin remove-content action');
  else bad('reply still present after remove-content — count=' + replyGone);
  await admin.screenshot({ path: `${OUT}/07-after-remove.png`, fullPage: true });

  // ── 8. Admin deletes the entire thread ────────────────────────────
  step(8, 'Admin deletes the whole thread');
  admin.once('dialog', d => d.accept());
  await admin.locator('form[action$="/forums/t/' + threadId + '"][method="POST"]:has(input[value="DELETE"]) button').click();
  await admin.waitForLoadState('domcontentloaded');
  // hitting the thread URL again should 404 / redirect.
  const afterDelete = await admin.goto(threadUrl);
  if (afterDelete.status() === 404) ok('thread URL now 404s after admin delete');
  else note('thread URL returned ' + afterDelete.status() + ' (expected 404)');
  await admin.screenshot({ path: `${OUT}/08-after-thread-delete.png`, fullPage: true });

  // ── 9. Anyone (anon) can view trainer and admin public profiles ──
  step(9, 'Anonymous user can view both public profiles');
  // get the IDs by visiting leaderboard or /u/{id} — we know id=1 admin, id=2 trainer from seeder order, but fetch via API page.
  // Simpler: derive from the thread page we still have in admin context? It's gone. Hit /leaderboard.
  // Just try /u/1 and /u/2.
  for (const uid of [1, 2, 3]) {
    const r = await anon.goto(BASE + '/u/' + uid);
    note(`/u/${uid} → ${r.status()}`);
    if (r.status() === 200) {
      // Should show a name on the page
      const name = await anon.locator('h1, h2').first().textContent();
      ok(`/u/${uid} loads (200), name shown: "${(name||'').trim().slice(0,40)}"`);
      await anon.screenshot({ path: `${OUT}/09-profile-${uid}.png`, fullPage: true });
    } else if (r.status() === 404) {
      note(`/u/${uid} 404 (user may not exist)`);
    } else {
      bad(`/u/${uid} unexpected status ${r.status()}`);
    }
  }

  console.log('\n=== summary ===');
  if (allErrors.length) {
    console.log('Server / JS errors observed:');
    for (const e of allErrors) console.log('  ! ' + e);
    process.exitCode = 1;
  } else {
    console.log('No 5xx or uncaught JS errors observed.');
  }

  await browser.close();
}

main().catch(e => { console.error(e); process.exit(1); });
